### ISSUE TITLE
Add user photo

### ISSUE THREAD

**Issue by hazemahmedx0** [7adidaz/E7fazly#19]
Every user should have one of these images (random)

![image](https://github.com/7adidaz/E7fazly/assets/88671390/2f56b0e9-0a4a-4cfb-be2a-02ef89fd2137)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/f5204781-49b3-4187-886b-28fa257d394d)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/fe41c8ed-c38f-4a50-89af-bdaa4cc70a37)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/0bbb1cef-6258-4f76-b229-e8792cf4fa4e)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/5b5e19a0-2feb-4a30-84bf-e77ddedce8e1)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/4391c431-f1c6-446d-b009-2b29f93de29c)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/2762e887-940b-4b22-ad6e-9295e46de0a9)
![image](https://github.com/7adidaz/E7fazly/assets/88671390/0d4f7f40-c285-4a9f-bb9d-41425dc323c9)

**Comment by 7adidaz** [comment]
solved.
